// <auto-generated />
namespace CommunitiyMedicineApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VoterIdTypeChangedIntoint64AndnumberofServiceGiveIsAddedInTreatment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VoterIdTypeChangedIntoint64AndnumberofServiceGiveIsAddedInTreatment));
        
        string IMigrationMetadata.Id
        {
            get { return "201702190359302_VoterIdTypeChangedIntoint64AndnumberofServiceGiveIsAddedInTreatment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
